environment: &env
- PYTHONUNBUFFERED=1
- PYTHONDONTWRITEBYTECODE=1
- TERM=xterm-256color
- MYSQL_ROOT_PASSWORD=bedrock
- DATABASE_URL=mysql://root:bedrock@mysql/bedrock
- EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
- ALLOWED_HOSTS='*'

debugenv: &debugenv
- DEBUG=1
- PYTHONUNBUFFERED=1
- PYTHONDONTWRITEBYTECODE=1
- TERM=xterm-256color
- MYSQL_ROOT_PASSWORD=bedrock
- DATABASE_URL=mysql://root:bedrock@mysql/bedrock

bedrock:
  image: mozorg/bedrock
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  environment: *debugenv

bedrockbuild:
  build: apache/bedrock/base
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  environment: *debugenv

mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment: *env

apache:
  image: mozorg/apache
  ports:
    - "80:80"
  environment: *env
  command: httpd -DFOREGROUND
  working_dir: /data/www/www.mozilla.org-django/bedrock

apachebuild:
  build: apache
  ports:
    - "80:80"
  environment: *env
  command: httpd -DFOREGROUND
