environment: &env
- PYTHONUNBUFFERED=1
- PYTHONDONTWRITEBYTECODE=1
- TERM=xterm-256color
- MYSQL_ROOT_PASSWORD=bedrock

bedrock:
  build: apache/bedrock/base
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  environment: *env

mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment: *env

apache:
  build: apache
  ports:
    - "80:80"
  environment: *env
  command: httpd -DFOREGROUND