mysql:
  extends:
    file: base.yml
    service: mysql

bedrock:
  extends:
    file: base.yml
    service: bedrockbuild
  volumes:
    - bedrock:/app
    - apache/mozilla.com:/data/www/www.mozilla.org
  links:
    - mysql

apache:
  extends:
    file: base.yml
    service: apachebuild
  volumes:
    - apache/mozilla.com:/data/www/www.mozilla.org
    - bedrock:/data/www/www.mozilla.org-django/bedrock
  links:
    - mysql